### ISSUE TITLE
Open Data zum Thema Familie #3

### ISSUE THREAD

**Issue by jahnique** [codeformuenster/open-data#14]
- [ ] Freibäder/Hallenbäder/Badeseen (Beckenlänge, Nichtschwimmer? Plantschbereich? Preise, ...)
- [ ] Campingplätze
- [ ] Cafes mit Spielecken
- [ ] Kitas, Plätze nach Altersstufen
- [ ] Öffentliche Parks und Gärten
- [ ] API für Veranstaltungskalender
- [ ] Apotheken- und Krankenhausstandorte mit Notfalldienst-Hinweis
- [ ] Büchereien / Bibliotheken
- [ ] Sehenswürdigkeiten
- [ ] Behindertenwohnheime
- [ ] Bio- / Fair Trade-Geschäfte

**Comment by ubergesundheit** [comment]
Geschlossen wegen #12
